### ISSUE TITLE
Support for remote debug

### ISSUE THREAD

**Issue by AgDude** [pouchdb/pouchdb-fauxton-chrome-extension#11]
Is there any way to support remote debugging? 

In this case I have pouchDB running in a cordova app on android, which I have connected to chrome as a remote debug session. the PouchDB tab in the extension is blank.

**Comment by marten-de-vries** [comment]
It might be possible to extend the addon to do something like this, but it certainly doesn't support it now. And to be honest, I wouldn't know how to go about that. You could try running fauxton directly in your app/in an iframe, though (so on the device):

https://github.com/pouchdb/pouchdb-fauxton-logic
