### ISSUE TITLE
This not work with Ionic in Browser?

### ISSUE THREAD

**Issue by ghost** [pouchdb/pouchdb-fauxton-chrome-extension#13]
Hi!
 I'm develop apps with Ionic running in Chrome Browser, with command `ionic serve`. I maked a test app with PounchDB for a WebApp (Is very good), and i used the PounchDB Inspector, for debug my tasks. But when i try use PounchDB Inspector with Ionic Apps running on browser, this not take info's about the app.

For test Ionic apps in browser using PounchDB, i not use the adapter Cordova, being using WebSQL adapter, and the data is visible in Application > Storage tab. But not is showed by PounchDB Inspector.

Someone know how i can debug storage ionic apps in browser using Pounch Inspect ?

**Comment by marten-de-vries** [comment]
Pretty sure websql databases are unsupported. You could try to make a new db inside the PouchDB Inspector pane with the same name as the database you want to inspect. If you're lucky, it'll show you the data already in there. I don't know for sure if  that'll work, but it's worth a shot.

**Comment by ghost** [comment]
I'm using cordova sqlite to save the db file inside folder app, and not using websql.  Another way a can inspect the db is exporting the db file from device to my desktop and using tools for debug sqlite db's.Its not is the best way but is helpfull.
