### ISSUE TITLE
Memory leak ??

### ISSUE THREAD

**Issue by Geolim4** [pouchdb/pouchdb-fauxton-chrome-extension#14]
Hello,

I'm using this extension since while now, but unfortunately there's a huge memory leak :(
Can you please try to fix it ?

Cheers,
Georges

**Comment by genu** [comment]
I notice this issue as well. Not sure where its caused, but after a while CPU usage sky rockets and I have to kill the extension to bring the cpu usage back to normal.

**Comment by sebastiangrebe** [comment]
For me this happens also when there is actually no pouchdb running in any of my tabs.
