### ISSUE TITLE
Extention stoped working in Chrome version 60

### ISSUE THREAD

**Issue by broerse** [pouchdb/pouchdb-fauxton-chrome-extension#17]
Hi this extension stopped working on Windows after I updated Chrome from version 59 to 60. It only shows a spinner and not the database.

**Comment by jkeczan** [comment]
Same issue for me

**Comment by onearmfrog** [comment]
Same for me :(

**Comment by jancona** [comment]
I'm also seeing this. In Chrome 59 I was seeing this message:

[Deprecation] indexedDB.webkitGetDatabaseNames() is deprecated and will be removed in M60, around August 2017. See https://www.chromestatus.com/features/5725741740195840 for more details.

See also https://github.com/pouchdb/pouchdb/issues/6469

**Comment by marten-de-vries** [comment]
That's probably for the best; Fauxton is useless if you cannot choose which database to inspect.

If anyone wants to pursue making a similar extension, my recommendation would be not to hack Fauxton into Fauxton's http request handling like this extension did any further, but to write a dedicated interface instead. Part of it would be asking the user which database to inspect (by tying the name).

I'm not planning on doing that myself for now.

**Comment by broerse** [comment]
@marten-de-vries  It seems we have to wait for [this](https://github.com/w3c/IndexedDB/issues/31) but it could take years. Perhaps remove the extension from chrome until this is fixed. Many thanks for your work on this extension!

**Comment by marten-de-vries** [comment]
@broerse Right, just unpublished the extension.

**Comment by broerse** [comment]
@marten-de-vries it should say`Unmaintained: see issue #17` not #16

**Comment by marten-de-vries** [comment]
Thanks! Updated.

**Comment by shennan** [comment]
For now we should remove this part of the PouchDB Guid:

<img width="740" alt="screen shot 2017-12-03 at 11 37 20" src="https://user-images.githubusercontent.com/1840398/33525005-84752b0a-d81e-11e7-90f6-ae7dfcd4effc.png">

https://pouchdb.com/guides/databases.html#debugging

I have [opened an issue here](https://github.com/pouchdb/pouchdb/issues/6908)

**Comment by Ravenstine** [comment]
I made a change to pouchdb-fauxton-logic that allows the extension to continue working in the latest versions of Chrome.  It gets the list of databases from the `pouch__all_dbs__` database through PouchDB rather than from the deprecated webkit IndexedDB function.  I don't know what the downsides to doing this are, though I suspect this means some kinds of databases might not show up.  For my own purposes, I don't care so long as I can create/read/update/delete records in the database my application creates.

If you want to try it yourself, just build the extension with my fork of pouchdb-fauxton-logic:
https://github.com/ravenstine/pouchdb-fauxton-logic

**Comment by marten-de-vries** [comment]
@Ravenstine I did not originally do that because it requires the ``pouchdb-all-dbs`` plugin to be active whenever a database is created/removed. Nice workaround, though.

**Comment by bean5** [comment]
> Right, just unpublished the extension.

@marten-de-vries

Main README says it is still says it is available. Dead link, of course. Sad.

**Comment by floer32** [comment]
for posterity: https://stackoverflow.com/a/46559775/884640

> I know it's not the same thing, but if you use WebSQL or IndexedDB, You can use normal developer tools provided by Chrome, going to Application/Storage and then look at data in your DB. It is also explained in the official PouchDB documentation at https://pouchdb.com/guides/databases.html

**Comment by LifeIsStrange** [comment]
@broerse it did take years but IDBfactory.databases() is now widely supported 🚀
https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases
Can this extension be resurrected? :)

**Comment by LifeIsStrange** [comment]
I have made a [pull request](https://github.com/pouchdb/pouchdb-fauxton-logic/pull/2) that should make the extension work again!
However, even with an old node and npm version I have dependencies issues which I don't know how to fix..
@jancona

There is a version of the extension online:
https://ma.rtendevri.es/fauxton/

I have no idea how to build the project, maybe that I don't have the exactly right node and npm version, if so what are them??

**Comment by LifeIsStrange** [comment]
Well I managed to make it works again!
![image](https://user-images.githubusercontent.com/12934716/141181622-30d2fce8-7c66-4288-b444-2c1b7858d495.png)

@jancona @broerse @hangtwenty @bean5
@marten-de-vries @Ravenstine @daleharvey
@shennan @darkdadi @onearmfrog @jkeczan
