### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by barbalex** [pouchdb/pouchdb-fauxton-chrome-extension#2]
Hi

I install the extension. Then open it in the developer tools in my project's page. It doesn't show anything besides the basic layout. I refresh the window. Still nothing. I check in the extensions list and it says by pouchdb-fauxton: "Diese Erweiterung ist möglicherweise beschädigt." (="This extension could be broken").

I have exposed PouchDB as window.PouchDB, see here: https://github.com/barbalex/oi/blob/master/src/modules/nav/initiateNav.js#L14

Am I doing something wrong?

Thanks for this great tool.

Alex

**Comment by marten-de-vries** [comment]
Seems like I did something wrong, I used the wrong version of browserify to 'build' the extension which gave problems. Please try the new latest version (0.1.1) instead. It's again in the chrome web store.

**Comment by barbalex** [comment]
bingo
neat: the tool was automatically updated

thanks!

**Comment by marten-de-vries** [comment]
Nice! Thanks for reporting back.
