### ISSUE TITLE
Exposing PouchDB to window

### ISSUE THREAD

**Issue by ArnoBuschmann** [pouchdb/pouchdb-fauxton-chrome-extension#3]
Hello,

I installed the chrome extension and got the error message "No PouchDB found. To use the current page with PouchDB-Fauxton, window.PouchDB needs to be set."

So to expose PouchDB to window I did:

``` javascript
var db = new PouchDB('localpouchdb');
if (typeof window != "undefined") {window.PouchDB = db};
```

But I still get an empty Fauxton layout. How can I fix this?

**Comment by marten-de-vries** [comment]
You shouldn't do `window.PouchDB = db;` but `window.PouchDB = PouchDB;`. That should fix it.

**Comment by ArnoBuschmann** [comment]
Umm, embarrassing. Yes, that works, thank you! :)

**Comment by ArnoBuschmann** [comment]
Oh well, it was there. I have been compacting the DB with it. Thereafter it was gone again. So I deleted the DB and made up a new one, still gone. That's strange, any idea?

**Comment by ArnoBuschmann** [comment]
Ok, what I see now is, that Fauxton gets lost with a reload but is available again when opening a new tab.

**Comment by naivefun** [comment]
This is not working in wrapped framework like angular2, vuejs.
Especially when angular2 comes with Typescript, is there a way to fix it?

**Comment by marten-de-vries** [comment]
No way around it; the extension needs access to the application's PouchDB object, to prevent version data model incompatibilities. In my experience, it's pretty much always possible to add PouchDB to the window object. It might be hacky (like temporarily changing code in dependencies), but it's probably possible.

**Comment by naivefun** [comment]
The workaround is actually very easy:

``` javascript
    System.import('pouchdb').then(function (PouchDB) {
        window.PouchDB = PouchDB;
    });
```

maybe it shouldn't be used in production though.

**Comment by qtleeq** [comment]
@naivefun Where did you put that? I am using angular-cli 1.0.0-rc.2.

**Comment by rjcorwin** [comment]
@TaylorDennisLee [This PR](https://github.com/Tangerine-Community/Tangerine/pull/375/files) shows how we added support for PouchDB inspector in our Angular 4 application. Cheers!
